#!/usr/bin/env python3

# gpxviewer
#
# Copyright (C) 2016 Sergey Salnikov <salsergey@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import sys
from PyQt5.QtCore import QCoreApplication, QLocale, QTranslator
from PyQt5.QtWidgets import QApplication


app = QApplication(sys.argv)

translator = QTranslator()
if not translator.load(QLocale(), 'gpxviewer', '_', QCoreApplication.applicationDirPath() + '/../share/gpxviewer/translations'):
  translator.load(QLocale(), 'gpxviewer', '_', '/'.join(sys.argv[0].split('/')[:-1]) + '/data')
QCoreApplication.installTranslator(translator)

# We need to install translator first
from gpxviewer.gpxmainwindow import GpxMainWindow

my_mainWindow = GpxMainWindow()
my_mainWindow.show()
sys.exit(app.exec_())
