# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setWindowTitle("GPX Viewer")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gpxView = QtWidgets.QTableView(self.centralwidget)
        self.gpxView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.gpxView.setObjectName("gpxView")
        self.gpxView.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.gpxView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFilter = QtWidgets.QMenu(self.menubar)
        self.menuFilter.setObjectName("menuFilter")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.secondaryToolBar = QtWidgets.QToolBar(MainWindow)
        self.secondaryToolBar.setMovable(False)
        self.secondaryToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.secondaryToolBar.setObjectName("secondaryToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.secondaryToolBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("."), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon)
        self.actionQuit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAboutQt = QtWidgets.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setIcon(icon)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionLoadGPXfile = QtWidgets.QAction(MainWindow)
        self.actionLoadGPXfile.setIcon(icon)
        self.actionLoadGPXfile.setShortcut("Ctrl+L")
        self.actionLoadGPXfile.setObjectName("actionLoadGPXfile")
        self.actionDistanceProfile = QtWidgets.QAction(MainWindow)
        self.actionDistanceProfile.setIcon(icon)
        self.actionDistanceProfile.setShortcut("Ctrl+P")
        self.actionDistanceProfile.setObjectName("actionDistanceProfile")
        self.actionTimeProfile = QtWidgets.QAction(MainWindow)
        self.actionTimeProfile.setIcon(icon)
        self.actionTimeProfile.setShortcut("Ctrl+T")
        self.actionTimeProfile.setObjectName("actionTimeProfile")
        self.actionProfileStyle = QtWidgets.QAction(MainWindow)
        self.actionProfileStyle.setIcon(icon)
        self.actionProfileStyle.setObjectName("actionProfileStyle")
        self.actionShowSkipped = QtWidgets.QAction(MainWindow)
        self.actionShowSkipped.setCheckable(True)
        self.actionShowSkipped.setObjectName("actionShowSkipped")
        self.actionShowMarked = QtWidgets.QAction(MainWindow)
        self.actionShowMarked.setCheckable(True)
        self.actionShowMarked.setObjectName("actionShowMarked")
        self.actionShowCaptioned = QtWidgets.QAction(MainWindow)
        self.actionShowCaptioned.setCheckable(True)
        self.actionShowCaptioned.setObjectName("actionShowCaptioned")
        self.actionShowOther = QtWidgets.QAction(MainWindow)
        self.actionShowOther.setCheckable(True)
        self.actionShowOther.setObjectName("actionShowOther")
        self.actionGpxViewerHelp = QtWidgets.QAction(MainWindow)
        self.actionGpxViewerHelp.setObjectName("actionGpxViewerHelp")
        self.actionAboutGPXViewer = QtWidgets.QAction(MainWindow)
        self.actionAboutGPXViewer.setObjectName("actionAboutGPXViewer")
        self.menuFile.addAction(self.actionLoadGPXfile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionGpxViewerHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAboutQt)
        self.menuHelp.addAction(self.actionAboutGPXViewer)
        self.menuFilter.addAction(self.actionShowSkipped)
        self.menuFilter.addAction(self.actionShowMarked)
        self.menuFilter.addAction(self.actionShowCaptioned)
        self.menuFilter.addAction(self.actionShowOther)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionLoadGPXfile)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSaveAs)
        self.toolBar.addSeparator()
        self.secondaryToolBar.addAction(self.actionProfileStyle)
        self.secondaryToolBar.addSeparator()
        self.secondaryToolBar.addAction(self.actionDistanceProfile)
        self.secondaryToolBar.addAction(self.actionTimeProfile)

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.actionOpen.triggered.connect(MainWindow.fileOpen)
        self.actionAboutQt.triggered.connect(MainWindow.aboutQt)
        self.actionDistanceProfile.triggered.connect(MainWindow.plotDistanceProfile)
        self.actionTimeProfile.triggered.connect(MainWindow.plotTimeProfile)
        self.actionSave.triggered.connect(MainWindow.fileSave)
        self.actionSaveAs.triggered.connect(MainWindow.fileSaveAs)
        self.actionLoadGPXfile.triggered.connect(MainWindow.loadGPXFile)
        self.actionProfileStyle.triggered.connect(MainWindow.showProfileStyleOptions)
        self.actionShowSkipped.triggered['bool'].connect(MainWindow.showSkipped)
        self.actionShowMarked.triggered['bool'].connect(MainWindow.showMarked)
        self.actionShowOther.triggered['bool'].connect(MainWindow.showOther)
        self.actionShowCaptioned.triggered['bool'].connect(MainWindow.showCaptioned)
        self.actionGpxViewerHelp.triggered.connect(MainWindow.gpxViewerHelp)
        self.actionAboutGPXViewer.triggered.connect(MainWindow.aboutGPXViewer)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuFilter.setTitle(_translate("MainWindow", "F&ilter"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionOpen.setText(_translate("MainWindow", "&Open project"))
        self.actionAboutQt.setText(_translate("MainWindow", "&About Qt"))
        self.actionSave.setText(_translate("MainWindow", "&Save project"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save project &as..."))
        self.actionLoadGPXfile.setText(_translate("MainWindow", "&Load GPX file"))
        self.actionDistanceProfile.setText(_translate("MainWindow", "&Distance profile"))
        self.actionTimeProfile.setText(_translate("MainWindow", "&Time profile"))
        self.actionProfileStyle.setText(_translate("MainWindow", "Profile &style"))
        self.actionShowSkipped.setText(_translate("MainWindow", "&Show skipped"))
        self.actionShowMarked.setText(_translate("MainWindow", "Show &marked"))
        self.actionShowCaptioned.setText(_translate("MainWindow", "Show &captioned"))
        self.actionShowOther.setText(_translate("MainWindow", "Show &other"))
        self.actionGpxViewerHelp.setText(_translate("MainWindow", "GPX Viewer &Help"))
        self.actionAboutGPXViewer.setText(_translate("MainWindow", "About &GPX Viewer"))

